-- 78_VADSTENA_SPOKVANDRING_PLATSER.sql
-- Importerad från scraper-visit-sidor/data/vadstena-spokvandring/ (Grantigos eget
-- researchmaterial för Spökvandring i Vadstena — 7 stopp + 2 bonus).
-- Kolumnskydd för delade DB-kolumner som äldre migrationer inte skapar:
ALTER TABLE places ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS translations JSONB;


BEGIN;
INSERT INTO places (id, name, slug, lat, lng, country, region, type, scary, free, bookable, teaser, description, status, source, translations) VALUES
-- OBS: 'vadstena-slott' finns redan live (09_IMPORT) — vi återanvänder id+slug så
-- ON CONFLICT BERIKAR den befintliga platsen i stället för att skapa en dubblett.
('vadstena-slott', 'Vadstena slott', 'vadstena-slott', 58.4459556, 14.8826411, 'Sverige', 'Östergötland', 'Slott', 3, true, false,
 'Renässansborgen där hertig Magnus, Gustav Vasas psykiskt sjuke son, enligt sägnen kastade sig ur fönstret mot en sjöjungfru i vallgraven.',
 'Vadstena slott byggdes från 1545 på Gustav Vasas order. Hit satte kungen sin tredje son, hertig Magnus, som från 1560-talet greps av svår psykisk sjukdom och 1574 fråntogs makten (historiskt belagt). Sägnen berättar att Magnus en vårkväll såg en sjöjungfru stiga ur Vättern och kastade sig ut genom fönstret ner i vallgraven — där vakterna fann honom oskadd och leende. Sägnen lever i folkvisan "Herr Magnus och havstrollet". Modernt rykte: en gestalt i renässanskläder på balkongen i kanonsalen.',
 'published', 'vadstena-spokvandring-research',
 '{"en":{"name":"Vadstena Castle","teaser":"The Renaissance fortress where Duke Magnus, Gustav Vasa''s mentally ill son, is said to have thrown himself from a window toward a mermaid in the moat.","description":"Vadstena Castle was begun in 1545 for Gustav Vasa. His third son, Duke Magnus, ruled here until severe mental illness cost him power in 1574 (documented). Legend says Magnus saw a mermaid rise from Lake Vättern one spring evening and hurled himself into the moat, where guards found him unharmed and smiling. The tale survives in folk ballads. Modern rumour tells of a figure in Renaissance dress on the cannon-hall balcony."}}'::jsonb),

('vadstena-spokvandring-02-radhustorget', 'Rådhustorget & Rödtornet', 'vadstena-spokvandring-02-radhustorget', 58.4472400, 14.8880714, 'Sverige', 'Östergötland', 'Rättsplats', 2, true, false,
 'Sveriges äldsta bevarade rådhus med en medeltida arrestcell i botten — och Rödtornet, allt som återstår av en kyrka som brann 1423.',
 'Rådhuset (äldsta delar ca 1460) är Sveriges äldsta bevarade. I bottenvåningen murades på 1500-talet en tunnvälvd arrestcell där dömda hölls. Rödtornet är klocktornet från den försvunna stadskyrkan S:t Per ("Rödkyrkan"), som brann i stadsbranden 1423; kring den låg stadens kyrkogård. Tema: rättskipning och de tidiga häxprocesserna i Östergötland (dödsstraff i trolldomslagen 1608) — dock skedde bränningarna i Söderköping/Finspång, inte i Vadstena stad. Ingen egen spöksägen; autentisk rätts- och straffhistoria.',
 'published', 'vadstena-spokvandring-research',
 '{"en":{"name":"Town Hall Square & the Red Tower","teaser":"Sweden''s oldest surviving town hall, with a medieval jail cell below — and the Red Tower, all that remains of a church that burned in 1423.","description":"Vadstena''s town hall (oldest parts c. 1460) is the oldest surviving in Sweden, with a vaulted 16th-century jail cell in its base. The Red Tower is the bell tower of the vanished S:t Per church, lost in the 1423 town fire. A place to tell of justice, punishment and Östergötland''s early witch trials (executions took place in Söderköping and Finspång, not Vadstena itself)."}}'::jsonb),

('vadstena-spokvandring-03-klosterkyrkan', 'Klosterkyrkan (Blåkyrkan)', 'vadstena-spokvandring-03-klosterkyrkan', 58.4507709, 14.8915378, 'Sverige', 'Östergötland', 'Kyrka', 2, true, false,
 'Sankta Birgittas kyrka, där reliker vilar i ett rött skrin — och där forskning 2010 visade att den utställda "Birgittas skalle" troligen inte är hennes.',
 'Blåkyrkan invigdes 1384 på den heliga Birgittas initiativ. Hennes kvarlevor fördes hem från Rom; legenden berättar om mirakel längs vägen (blinda som såg, lama som gick). Delar av skelettet vilar i ett rött relikskrin bakom högaltaret. Dokumenterat mysterium: 2010 fann forskare vid Uppsala universitet att den utställda "Birgittas skalle" och "dottern Katarinas skalle" varken var släkt eller från rätt tid — skallen tillhör sannolikt inte Birgitta.',
 'published', 'vadstena-spokvandring-research',
 '{"en":{"name":"Abbey Church (the Blue Church)","teaser":"Saint Birgitta''s church, where relics rest in a red shrine — and where 2010 research showed the displayed \"skull of Birgitta\" is probably not hers.","description":"The Blue Church was consecrated in 1384 on Saint Birgitta''s initiative. Her remains were brought back from Rome amid legends of miracles. Part of the skeleton rests in a red reliquary behind the high altar. A documented mystery: in 2010 Uppsala University researchers found the displayed \"skull of Birgitta\" was neither related to nor from the same era as the supposed skull of her daughter — it is likely not Birgitta''s at all."}}'::jsonb),

('vadstena-spokvandring-04-svarta-nunnan', 'Klosterträdgården — Den svarta nunnan', 'vadstena-spokvandring-04-svarta-nunnan', 58.4512000, 14.8908000, 'Sverige', 'Östergötland', 'Sägenplats', 5, true, false,
 'I klosterträdgården sägs Den svarta nunnan glida längs muren om nätterna — en nunna som dödade sitt barn och aldrig fann ro.',
 'Vadstenas läskigaste sägen. När klostret tömdes kring år 1600 reste de flesta nunnorna till Danzig — men en kom aldrig med, för hon var redan död. Enligt sägnen fann man barnskelett i trädgården, tolkade som frukten av hemliga möten mellan munkar och nunnor; en av mödrarna ska ha dödat sitt nyfödda barn och därför inte funnit ro. Hon glider längs muren och Murgatan nattetid, följd av plötslig kyla och skrämda djur. Källkritik: en vandringssägen som finns på flera håll i landet, utan historiskt belägg — men djupt rotad lokal folklore.',
 'published', 'vadstena-spokvandring-research',
 '{"en":{"name":"Abbey Garden — the Black Nun","teaser":"In the abbey garden the Black Nun is said to glide along the wall at night — a nun who killed her child and never found rest.","description":"Vadstena''s most chilling legend. When the abbey emptied around 1600 most nuns left for Danzig — but one never went, for she was already dead. Legend says infant skeletons were found in the garden, blamed on secret trysts between monks and nuns; one mother is said to have killed her newborn and so cannot rest. She glides along the wall and Murgatan at night amid sudden cold and frightened animals. A migratory legend with no historical proof — but deeply rooted local folklore."}}'::jsonb),

('vadstena-spokvandring-05-stora-darhuset', 'Stora Dårhuset / Hospitalmuseet', 'vadstena-spokvandring-05-stora-darhuset', 58.4515763, 14.8940973, 'Sverige', 'Östergötland', 'Sjukhus', 4, true, false,
 'Sveriges första dårhus (1757), byggt för "eländiga, vanvettiga och rasande". Av de bortglömda döda finns bara en enda gravsten kvar.',
 'Stora Dårhuset restes 1757 (ritat av C.J. Cronstedt) som Sveriges första byggnad enbart för psykiskt sjuka — ursprungligen tolv "eländiga, vanvettiga och rasande" patienter, i celler kring en mörk korridor, bakom en mur. Antalet växte till över 1 100 på 1960-talet; "Vadstena" blev ett skällsord för galenskap. De döda som ingen hemförsamling ville ta emot begravdes på en egen kyrkogård; idag återstår en enda gravsten — Lars Wilhelm Gahne (1837–1857), som kom hit 17-årig med epilepsi och dog tre år senare. Allt historiskt belagt — den sanna skräcken.',
 'published', 'vadstena-spokvandring-research',
 '{"en":{"name":"The Great Madhouse / Hospital Museum","teaser":"Sweden''s first madhouse (1757), built for the \"wretched, insane and raving\". Of its forgotten dead, only a single gravestone remains.","description":"The Great Madhouse was built in 1757 (by C.J. Cronstedt) as Sweden''s first building solely for the mentally ill — originally twelve \"wretched, insane and raving\" patients in cells around a dark corridor, behind a wall. Numbers grew past 1,100 by the 1960s, and \"Vadstena\" became a byword for madness. The dead no parish would claim were buried in their own graveyard; today one gravestone remains — Lars Wilhelm Gahne (1837–1857), who arrived aged 17 with epilepsy and died three years later. All documented — the true horror."}}'::jsonb),

('vadstena-spokvandring-06-marten-skinnare', 'Mårten Skinnares hus', 'vadstena-spokvandring-06-marten-skinnare', 58.4516203, 14.8944162, 'Sverige', 'Östergötland', 'Medeltidshus', 2, true, false,
 'Det medeltida stenhuset där en köpman 1519 grundade hospitalet för fattiga och pilgrimer — vaggan för Sveriges psykiatrivård.',
 'Ett av Sveriges bäst bevarade medeltida stenhus, byggt på 1500-talet av den rike köpmannen Mårten Nilsson "Skinnare". År 1519 fick han mark vid klostret för att uppföra ett hospital — en sjukstuga för fattiga, pilgrimer och sjuka. Här började hela Vadstenas 600-åriga vårdhistoria, som slutade i dårhusets celler intill. Historiskt belagt; ett stilla, reflekterande stopp.',
 'published', 'vadstena-spokvandring-research',
 '{"en":{"name":"Mårten Skinnare''s House","teaser":"The medieval stone house where a merchant founded a hospital for the poor and for pilgrims in 1519 — the cradle of Swedish psychiatric care.","description":"One of Sweden''s best-preserved medieval stone houses, built in the 16th century by the wealthy merchant Mårten Nilsson \"Skinnare\". In 1519 he was granted land by the abbey to found a hospital for the poor, pilgrims and the sick. Here Vadstena''s 600-year history of care began — a history that ended in the madhouse cells next door. Documented; a quiet, reflective stop."}}'::jsonb),

('vadstena-spokvandring-07-hamnen', 'Hamnen / Vättern', 'vadstena-spokvandring-07-hamnen', 58.4459100, 14.8814703, 'Sverige', 'Östergötland', 'Sägenplats', 3, true, false,
 'Vid det trodda bottenlösa Vättern bor Näcken och Sjöfrun — och 1897 ska ett odjur ha rest sig ur djupet utanför Vadstena.',
 'Finalstopp vid vattnet. Vättern troddes länge vara bottenlöst. Näcken, den vackre spelmannen, sägs locka lyssnare ut i djupet. Sjöfrun ska ha sitt hem vid ön Jungfrun utanför Vadstena och flytta sina palats till lugnare vatten före storm. En sjöodjurstradition finns också: 1897 ska ett stort mörkt väsen med två korta ben ha rest sig ur sjön och sedan försvunnit. Nedtecknad folktro; knyter tillbaka till hertig Magnus sjöjungfru vid slottet.',
 'published', 'vadstena-spokvandring-research',
 '{"en":{"name":"The Harbour / Lake Vättern","teaser":"At bottomless Lake Vättern dwell the Neck and the Lake Wife — and in 1897 a monster is said to have risen from the depths off Vadstena.","description":"The finale by the water. Vättern was long believed bottomless. The Neck, a beautiful fiddler, is said to lure listeners into the deep. The Lake Wife supposedly lives by the island Jungfrun off Vadstena and moves her palaces to calmer water before a storm. A lake-monster tradition survives too: in 1897 a large dark creature with two short legs is said to have risen and vanished. Recorded folklore that ties back to Duke Magnus''s mermaid at the castle."}}'::jsonb),

('vadstena-spokvandring-08-klosterhotell', 'Vadstena Klosterhotell', 'vadstena-spokvandring-08-klosterhotell', 58.4510790, 14.8907859, 'Sverige', 'Östergötland', 'Hotell', 4, true, true,
 'I de medeltida klosterhusen — som varit hospital, pesthus och sinnessjukhus — vaknar gäster av en vänlig äldre dam på sängkanten.',
 'Klosterhotellet ligger i medeltida klosterbyggnader som i sin tur varit hospital, pesthus, krigshärbärge och sinnessjukhus. Mest berättade spökrykte: "den pratsamma äldre damen" som gäster upplevt sittande på sängkanten — vänlig, ibland sorgsen, försöker tala innan hon försvinner. Även fotsteg i korridorer, dörrar som hålls, plötsliga temperaturfall. Modernt spökrykte (gäst- och personalanekdoter), ej historiskt styrkt. Passeras mellan stopp 4 och 5.',
 'published', 'vadstena-spokvandring-research',
 '{"en":{"name":"Vadstena Monastery Hotel","teaser":"In the medieval abbey buildings — once a hospital, plague house and asylum — guests wake to a kindly old woman on the edge of the bed.","description":"The hotel occupies medieval abbey buildings that also served as hospital, plague house, war lodging and asylum. Its best-known ghost story is \"the talkative old lady\" whom guests report sitting on the edge of the bed — kindly, sometimes sad, trying to speak before she vanishes. Also footsteps, doors held shut, sudden cold. Modern rumour from guest and staff anecdotes, not historically verified. Passed between stops 4 and 5."}}'::jsonb),

('vadstena-spokvandring-09-galgbacken', 'Galgbacken vid Kvarnbacken', 'vadstena-spokvandring-09-galgbacken', 58.441742, 14.914041, 'Sverige', 'Östergötland', 'Avrättningsplats', 5, true, false,
 'Stadens galgbacke, i bruk 1400–1650. Vid utgrävningen 2005 hittades ~25 avrättade unga män — en med en järnkrok driven genom skallen.',
 'Vadstenas avrättnings- och begravningsplats, i bruk ca 1400–1650, återfunnen av en slump 2004. Vid utgrävningen 2005 (RAÄ) grävdes omkring 25 skelett fram — nästan alla unga män, sannolikt hängda, tätt begravda. På en skalle satt en grov järnkrok driven genom benet. Arkeologiskt belagt (finns i din Fornsök-data, L2009:8448). Sägen ("det berättas"): byggnadsarbetare på 1930-talet hittade benbitar som doldes, och en dam i gammaldags kläder har synts där galgen stod. Bonusstopp ~1,5 km öster om centrum (bäst med bil).',
 'published', 'vadstena-spokvandring-research',
 '{"en":{"name":"The Gallows Hill at Kvarnbacken","teaser":"The town gallows, in use 1400–1650. A 2005 dig uncovered ~25 executed young men — one with an iron hook driven through the skull.","description":"Vadstena''s place of execution and burial, in use c. 1400–1650, rediscovered by chance in 2004. A 2005 excavation uncovered about 25 skeletons — nearly all young men, likely hanged, buried close together. One skull bore a heavy iron hook driven through the bone. Archaeologically documented (in your Fornsök data, L2009:8448). Legend: 1930s builders found bones that were hushed up, and a woman in old-fashioned dress has been seen where the gallows stood. A bonus stop ~1.5 km east of the centre."}}'::jsonb)

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, lat = EXCLUDED.lat, lng = EXCLUDED.lng, region = EXCLUDED.region,
  type = EXCLUDED.type, scary = EXCLUDED.scary, teaser = EXCLUDED.teaser,
  description = EXCLUDED.description, status = EXCLUDED.status, source = EXCLUDED.source,
  translations = EXCLUDED.translations;
COMMIT;
