-- 81_BERIKARE_SLOTT_2026_07_14.sql
-- Samlar den dagliga berikarens 7 databatchar (scraper-visit-sidor PR #1–#5, #7, #8)
-- så att de körs automatiskt av apply-db-workflowen — inget manuellt Supabase-steg.
-- 45 platser: SE-slott 6 · NO 2 · DK 5 · FI 4 · SE-herrgårdar 4 · UK-slott 12 · internationella 12.
-- Alla idempotenta (ON CONFLICT (id) DO UPDATE), dedupade mot live-DB av respektive batch.
ALTER TABLE places ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS translations JSONB;

-- hauntedplaces-slott-se-2026-07-14.sql  (svenska spökslott & herrgårdar, batch 1)
-- 6 nya platser till Hauntedplaces + Spökkartan (delat Supabase-projekt zffhdjogphqhcttkezsb).
-- Källa: svenska slott/herrgårdar via Wikidata + Wikipedia, spöksägner verifierade mot minst en
-- trovärdig källa (Wikipedia, slottens egna sidor, Myling Paranormal, Region Uppsala, lokalpress).
-- Deduplicerat mot 1305 live-platser (namn + koordinat <300 m) och mot data/hauntedplaces-*.sql.
-- Egen sv+en-text grundad i allmänt känd historia + folktro; källornas text återges ALDRIG ordagrant.
-- Idempotent: ON CONFLICT (id) DO UPDATE. Kör i Supabase SQL-editor (projekt zffhdjogphqhcttkezsb).

BEGIN;
INSERT INTO places (id, name, slug, lat, lng, country, region, type, scary, free, bookable, teaser, description, status, source, translations) VALUES
('angso-slott-vastmanland', 'Ängsö slott', 'angso-slott-vastmanland', 59.5325, 16.8575, 'Sverige', 'Västmanland', 'Slott', 4, false, true, 'På en ö i Mälaren sägs Karl XII:s hovnarr fortfarande vandra – nära 300 år efter sin död.', 'Ängsö slott reser sig på en holme i Mälaren och bär på flera spöksägner. Mest omtalad är Karl XII:s puckelryggige hovnarr Anders Luxemburg, som enligt traditionen ännu rör sig genom slottets salar långt efter sin död. Till stämningen hör också berättelser om skepnader och oförklarliga ljud i de gamla rummen. Slottet är byggnadsminne och öppnar för besök sommartid.', 'published', 'wikipedia', '{"en":{"name":"Ängsö Castle","teaser":"On an island in Lake Mälaren, Karl XII''s court jester is still said to walk — nearly 300 years after his death.","description":"Ängsö Castle stands on an islet in Lake Mälaren and carries several ghost legends. The best known concerns Anders Luxemburg, the hunchbacked court jester of King Karl XII, said by tradition to still move through the halls long after his death. Reports of shadowy figures and unexplained sounds add to the mood of the old rooms. The castle is a listed monument, open to visitors in summer."}}'::jsonb),
('svaneholms-slott-skane', 'Svaneholms slott', 'svaneholms-slott-skane', 55.50083, 13.47806, 'Sverige', 'Skåne, Skurup', 'Slott', 4, false, true, 'Renässansslottet i Skåne har en egen spökutställning – här sägs bland andra en dansande dansk kung och en vit fru gå igen.', 'Svaneholms slott i skånska Skurup är ett vattenomflutet renässansslott med så många spöksägner att det inrett en egen utställning om dem. Bland gestalterna som sägs hemsöka salarna finns den danske kungen Fredrik II som dansar i musiksalen, en vit fru och en grå munk. Många besökare har berättat om upplevelser de tolkat som övernaturliga. Slottet rymmer museum och restaurang och är öppet för besök.', 'published', 'wikipedia', '{"en":{"name":"Svaneholm Castle","teaser":"This Renaissance castle in Skåne even has its own ghost exhibition — a dancing Danish king and a White Lady are among those said to walk here.","description":"Svaneholm Castle in Skurup, Skåne, is a moated Renaissance castle with so many ghost legends that it has built an exhibition about them. Among the figures said to haunt its halls are the Danish king Frederick II dancing in the music room, a White Lady and a Grey Monk. Many visitors have described experiences they read as supernatural. The castle holds a museum and restaurant and is open to visitors."}}'::jsonb),
('skogaholms-herrgard-skansen', 'Skogaholms herrgård', 'skogaholms-herrgard-skansen', 59.32575, 18.10476, 'Sverige', 'Stockholm, Skansen', 'Herrgård', 3, false, true, 'Herrgården på Skansen bär på en mörk sägen om en budbärare som mördades för en väska full med pengar.', 'Skogaholms herrgård är en karolinsk herrgård som flyttades till friluftsmuseet Skansen i Stockholm. Till gården hör en gammal sägen om ett mord: en budbärare ska ha bragts om livet för en läderväska fylld med pengar, och en tjänare misstänktes för dådet. Berättelsen har följt med huset och ger den vackra 1700-talsmiljön en olustig underton. Herrgården visas som en del av Skansen.', 'published', 'wikipedia', '{"en":{"name":"Skogaholm Manor","teaser":"This manor at the Skansen open-air museum carries a dark legend of a messenger murdered for a bag full of money.","description":"Skogaholm Manor is a Carolean manor house relocated to the Skansen open-air museum in Stockholm. An old legend clings to it: a messenger is said to have been killed for a leather bag full of money, and a servant fell under suspicion. The tale has followed the house and lends its handsome 18th-century setting an uneasy undertone. The manor is shown as part of Skansen."}}'::jsonb),
('rosersbergs-slott-uppland', 'Rosersbergs slott', 'rosersbergs-slott-uppland', 59.57417, 17.84444, 'Sverige', 'Uppland, Sigtuna', 'Slott', 4, false, true, 'På det kungliga slottet dog en drottning 1818 – och en vaktpost sägs ha mött henne igen samma natt, med ett glas i handen.', 'Rosersbergs slott norr om Stockholm är ett av de kungliga slotten, och här avled drottning Hedvig Elisabet Charlotta år 1818. En nedärvd släktsägen berättar om en vaktpost vid hennes kista som hörde steg över det tomma golvet och plötsligt stod ansikte mot ansikte med den döda drottningen, som med hes röst räckte honom ett glas med en gulaktig dryck. Slottet är statligt byggnadsminne med bevarade sengustavianska interiörer och visningar sommartid.', 'published', 'myling', '{"en":{"name":"Rosersberg Palace","teaser":"A queen died at this royal palace in 1818 — and a sentry is said to have met her again that same night, a glass in her hand.","description":"Rosersberg Palace north of Stockholm is one of Sweden’s royal palaces, and Queen Hedvig Elisabet Charlotta died here in 1818. A family legend tells of a sentry at her coffin who heard footsteps across the empty floor and suddenly stood face to face with the dead queen, who in a hoarse voice held out a glass of a yellowish drink. The palace is a listed state monument with preserved late-Gustavian interiors and guided tours in summer."}}'::jsonb),
('sundbyholms-slott-sodermanland', 'Sundbyholms slott', 'sundbyholms-slott-sodermanland', 59.44778, 16.62389, 'Sverige', 'Södermanland, Eskilstuna', 'Slott', 3, false, true, 'Personalen kallar det Sörmlands spökrikaste slott – dörrar öppnas av sig själva och en svartklädd gestalt har setts i vinkällaren.', 'Sundbyholms slott vid Mälaren utanför Eskilstuna beskrivs ibland som Sörmlands spökrikaste slott. Personal och gäster har berättat om dörrar som öppnas och stängs på egen hand, nycklar som rasslar i tomma salar och handtag som trycks ner av sig själva. Efter en middag ska en lång, svartklädd gestalt med huva ha setts i vinkällaren. Ett medium lugnade enligt slottet med orden att här bara finns snälla spöken. I dag är Sundbyholm hotell och konferens vid Mälarens strand.', 'published', 'sundbyholms-slott', '{"en":{"name":"Sundbyholm Castle","teaser":"Staff call it Södermanland’s most haunted castle — doors open by themselves and a black-clad figure has been seen in the wine cellar.","description":"Sundbyholm Castle by Lake Mälaren outside Eskilstuna is sometimes called the most haunted castle in Södermanland. Staff and guests have told of doors that open and close on their own, keys rattling in empty halls and handles pressed down by unseen hands. After a dinner, a tall, black-clad hooded figure is said to have appeared in the wine cellar. A medium reportedly reassured the castle that only kind ghosts dwell here. Today Sundbyholm is a hotel and conference venue on the lakeshore."}}'::jsonb),
('wiks-slott-uppland', 'Wiks slott', 'wiks-slott-uppland', 59.73611, 17.46167, 'Sverige', 'Uppland, Uppsala', 'Slott', 4, false, true, 'En vit fru som drunknade på Mälarens is 1612 svävar här – och slår slottsuret tretton slag vaknar en fru ur 700 års sömn.', 'Wiks slott (Viks slott) i Uppland är en av Sveriges bäst bevarade medeltida borgar och har flera spöksägner. Den vita frun sägs vara Anna von der Grünau, som omkom på Mälarens is 1612; hon syns som en vitklädd kvinna svävande i dimman, med våta fotspår efter sig. Här talas också om en svart fru och om gamla fru Ramborg, som enligt sägnen vaknar ur sin 700-åriga sömn och visar sitt bleka ansikte i ett fönster de nätter slottsuret slår tretton slag. Slottet inrymmer folkhögskola och konferens och kan besökas.', 'published', 'regionuppsala', '{"en":{"name":"Wik Castle","teaser":"A White Lady who drowned on the lake ice in 1612 drifts here — and when the castle clock strikes thirteen, a lady wakes from 700 years of sleep.","description":"Wik Castle in Uppland is one of Sweden’s best-preserved medieval castles and holds several ghost legends. The White Lady is said to be Anna von der Grünau, who died on the ice of Lake Mälaren in 1612; she appears as a white-clad woman drifting through the mist, leaving wet footprints behind. There is also talk of a Black Lady and of old Lady Ramborg, who by legend wakes from her 700-year sleep and shows her pale face at a window on nights when the castle clock strikes thirteen. The castle houses a folk high school and conference venue and can be visited."}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name=EXCLUDED.name, teaser=EXCLUDED.teaser, description=EXCLUDED.description,
  country=EXCLUDED.country, region=EXCLUDED.region, type=EXCLUDED.type,
  lat=EXCLUDED.lat, lng=EXCLUDED.lng, scary=EXCLUDED.scary,
  translations=EXCLUDED.translations, status=EXCLUDED.status, source=EXCLUDED.source;
COMMIT;

-- hauntedplaces-slott-no-2026-07-14.sql  (norska spökslott & herrgårdar, batch 1)
-- 2 nya platser till Hauntedplaces + Spökkartan (delat Supabase-projekt zffhdjogphqhcttkezsb).
-- Källa: 139 norska slott/herregårder/fort via Wikidata + no/nn-Wikipedia; spöksägner verifierade mot
-- minst en trovärdig källa (Wikipedia, museernas sidor, boken "Ekte gjenferd").
-- Deduplicerat mot 69 live norska platser (namn + koordinat <400 m). Norge var redan tungt täckt
-- (Akershus, Nidaros, Elingård, Rød m.fl. redan live) → få nya. Kvalitet före kvantitet.
-- Egen sv+en-text grundad i allmänt känd historia + folktro; källornas text återges ALDRIG ordagrant.
-- Idempotent: ON CONFLICT (id) DO UPDATE. Kör i Supabase SQL-editor (projekt zffhdjogphqhcttkezsb).

BEGIN;
INSERT INTO places (id, name, slug, lat, lng, country, region, type, scary, free, bookable, teaser, description, status, source, translations) VALUES
('fossesholm-herregard-buskerud', 'Fossesholm herregård', 'fossesholm-herregard-buskerud', 59.72811, 9.86642, 'Norge', 'Buskerud, Øvre Eiker', 'Herrgård', 3, false, true, 'På herrgården sägs Halte-Birthe gå igen – flickan som hånades för att hon bara kunde räkna till tre och kastade sig ut genom ett fönster.', 'Fossesholm herregård i Vestfossen är en av Norges bäst bevarade 1700-talsherrgårdar och i dag en del av Buskerudmuseet. Till gården hör sägnen om Halte-Birthe – Birthe Svendsdatter – som hånades för att hon bara kunde räkna till tre och som enligt berättelsen kastade sig ut genom ett fönster på övervåningen på 1700-talet. Sedan dess sägs hon vandra som ett haltande, olyckligt spöke på gården. Herrgården är öppen för besök med utställningar och trädgård.', 'published', 'wikipedia', '{"en":{"name":"Fossesholm Manor","teaser":"At this manor, ''Limping Birthe'' is said to walk — the girl mocked for counting only to three, who threw herself from a window.","description":"Fossesholm Manor in Vestfossen is one of Norway''s best-preserved 18th-century manors and today part of the Buskerud Museum. It carries the legend of Limping Birthe — Birthe Svendsdatter — mocked for being able to count only to three, who by tradition threw herself from an upstairs window in the 1700s. Since then she is said to wander the estate as a limping, unhappy ghost. The manor is open to visitors, with exhibitions and gardens."}}'::jsonb),
('austad-gard-drammen', 'Austad gård', 'austad-gard-drammen', 59.73, 10.2058, 'Norge', 'Buskerud, Drammen', 'Herrgård', 3, false, true, 'På herrgården i Drammen sägs den svarta damen gå igen – den stolta amtmannsfrun Ingeborg Marie Glud från tidigt 1700-tal.', 'Austad gård är en gammal herrgård i Drammen med anor tillbaka till 1600-talet. Till huset knyts sägnen om den svarta damen, som sägs vara Ingeborg Marie Glud – den stolta amtmannsfrun som styrde gården i början av 1700-talet. Hon ska ännu röra sig genom rummen, klädd i svart. Gården med sin park är i dag ett omtyckt utflyktsmål nära Drammensälven.', 'published', 'ekte-gjenferd', '{"en":{"name":"Austad Manor","teaser":"At this Drammen manor, the ''Black Lady'' is said to walk — Ingeborg Marie Glud, the proud governor''s wife of the early 1700s.","description":"Austad Manor is an old estate in Drammen with roots in the 17th century. The house carries the legend of the Black Lady, said to be Ingeborg Marie Glud — the proud governor''s wife who ruled the estate in the early 1700s. She is said to still move through the rooms, dressed in black. Today the manor and its park are a favourite outing near the Drammen River."}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name=EXCLUDED.name, teaser=EXCLUDED.teaser, description=EXCLUDED.description,
  country=EXCLUDED.country, region=EXCLUDED.region, type=EXCLUDED.type,
  lat=EXCLUDED.lat, lng=EXCLUDED.lng, scary=EXCLUDED.scary,
  translations=EXCLUDED.translations, status=EXCLUDED.status, source=EXCLUDED.source;
COMMIT;

-- hauntedplaces-slott-dk-2026-07-14.sql  (danska spökslott & herrgårdar, batch 1)
-- 5 nya platser till Hauntedplaces + Spökkartan (delat Supabase-projekt zffhdjogphqhcttkezsb).
-- Källa: 794 danska slott/herregårder via Wikidata + da-Wikipedia; spöksägner verifierade mot minst
-- en trovärdig källa (Wikipedia, museer/slott, VisitFyn). Deduplicerat mot 54 live danska platser
-- OCH mot data/hauntedplaces-foreign-dk.sql (namn + koordinat <400 m). Dragsholm uteslöts —
-- fanns redan som 'dragsholm-slot-sjalland' i foreign-dk.sql. Egen sv+en-text; källornas text
-- återges ALDRIG ordagrant. Idempotent: ON CONFLICT (id) DO UPDATE.

BEGIN;
INSERT INTO places (id, name, slug, lat, lng, country, region, type, scary, free, bookable, teaser, description, status, source, translations) VALUES
('voergaard-slot-vendsyssel', 'Voergaard Slot', 'voergaard-slot-vendsyssel', 57.2425, 10.3354, 'Danmark', 'Jylland, Vendsyssel', 'Slott', 4, false, true, 'Den hårda slottsfrun Ingeborg Skeel sägs ännu återvända till renässansslottet i Vendsyssel.', 'Voergaard Slot i Vendsyssel är ett av Danmarks vackraste renässansslott, färdigt 1588. Dess mest omtalade spöke är Ingeborg Skeel, den hårda slottsfrun som av sina bönder upplevdes som en tyrann och som enligt sägnen återvänder till slottet gång på gång. Den långa raden av ägare och de mörka gångarna ger platsen en stämning av gången tid. Slottet rymmer i dag en konstsamling och är öppet för besök.', 'published', 'wikipedia', '{"en":{"name":"Voergaard Castle","teaser":"The hard mistress Ingeborg Skeel is still said to return to this Renaissance castle in Vendsyssel.","description":"Voergaard Castle in Vendsyssel is one of Denmark’s finest Renaissance castles, completed in 1588. Its most talked-about ghost is Ingeborg Skeel, the stern lady of the house whom her tenants experienced as a tyrant and who by legend returns to the castle again and again. The long line of owners and the dark passages lend the place an air of ages past. Today the castle holds an art collection and is open to visitors."}}'::jsonb),
('egeskov-slot-fyn', 'Egeskov Slot', 'egeskov-slot-fyn', 55.17639, 10.48944, 'Danmark', 'Fyn', 'Slott', 3, false, true, 'En liten trädocka måste få färsk halm varje jul – annars sägs slottet sjunka i vallgraven. Och en vit dam vandrar i parken.', 'Egeskov Slot på Fyn är en av Europas bäst bevarade vattenborgar, byggd mitt i en sjö på 1550-talet. Sägnen säger att en liten trädocka på tornvinden måste få färsk halm varje lillajulafton – annars sjunker slottet i vallgraven på julafton. Här går också en vit dam: en ung brud som drunknade i sjön när hästarna skenade och som sägs söka sin fästman i parken efter mörkrets inbrott. Slottet med sina trädgårdar och museer är ett av Danmarks mest besökta.', 'published', 'wikipedia', '{"en":{"name":"Egeskov Castle","teaser":"A little wooden figure must get fresh straw each Christmas — or the castle is said to sink into the moat. And a White Lady walks the park.","description":"Egeskov Castle on Funen is one of Europe’s best-preserved moated castles, built in the middle of a lake in the 1550s. Legend says a small wooden figure in the tower loft must be given fresh straw every Little Christmas Eve — or the castle will sink into the moat on Christmas Eve. A White Lady walks here too: a young bride who drowned in the lake when the horses bolted, said to search the park for her betrothed after dark. With its gardens and museums, the castle is one of Denmark’s most visited."}}'::jsonb),
('krenkerup-lolland', 'Krenkerup', 'krenkerup-lolland', 54.7769, 11.6703, 'Danmark', 'Lolland', 'Herrgård', 3, false, true, 'Det lolländska godset sägs hemsökas av en vit dam och av adelsmannen Palle Rosenkrantz gengångare.', 'Krenkerup är ett av Lollands största gods, med anor från medeltiden. Enligt traditionen hemsöks godset av flera gengångare – bland dem en vit dam och adelsmannen Palle Rosenkrantz. De gamla salarna och den vidsträckta parken ger platsen en stämning av svunna sekler. Godset är fortfarande i släkten Haugwitz-Hardenberg-Reventlows ägo.', 'published', 'wikipedia', '{"en":{"name":"Krenkerup","teaser":"This Lolland estate is said to be haunted by a White Lady and by the ghost of the nobleman Palle Rosenkrantz.","description":"Krenkerup is one of the largest estates on Lolland, with roots in the Middle Ages. By tradition the estate is haunted by several revenants — among them a White Lady and the nobleman Palle Rosenkrantz. The old halls and sweeping park lend the place the mood of vanished centuries. The estate remains in the Haugwitz-Hardenberg-Reventlow family."}}'::jsonb),
('irup-thy', 'Irup', 'irup-thy', 56.83344, 8.52999, 'Danmark', 'Jylland, Thy', 'Herrgård', 3, false, true, 'Vid fullmåne – helst en torsdag – sägs den vita damen ta en promenad genom parken på Irup.', 'Irup är en gammal herrgård i Thy på nordvästra Jylland. Många sägner är knutna till gården, och liksom flera danska herregårdar har Irup sin vita dam: vid fullmåne, helst en torsdag, sägs hon gå en tur genom parken ner mot vattnet. Gården är känd för sin långa historia och sitt goda jordbruk.', 'published', 'wikipedia', '{"en":{"name":"Irup Manor","teaser":"At full moon — best on a Thursday — the White Lady is said to take a walk through the park at Irup.","description":"Irup is an old manor in Thy in north-western Jutland. Many legends cling to the estate, and like several Danish manors Irup has its White Lady: at full moon, best on a Thursday, she is said to walk down through the park toward the water. The farm is known for its long history and fine agriculture."}}'::jsonb),
('starup-hovedgard-salling', 'Stårup Hovedgård', 'starup-hovedgard-salling', 56.5864, 9.11139, 'Danmark', 'Jylland, Salling', 'Herrgård', 3, false, true, 'På den gamla jyska herrgården sägs den grå damen gå igen – ett av gårdens många genfärd.', 'Stårup Hovedgård är en gammal herrgård i Salling på Jylland med rötter långt tillbaka i tiden. Som på så många danska herregårdar knyts spöksägner till huset – här berättas särskilt om den grå damen, ett genfärd som sägs röra sig genom de gamla rummen. Gården har genom seklen gått mellan olika släkter innan jorden styckades under 1900-talet.', 'published', 'wikipedia', '{"en":{"name":"Stårup Manor","teaser":"At this old Jutland manor the Grey Lady is said to walk — one of the estate’s many revenants.","description":"Stårup Manor is an old estate in Salling, Jutland, with roots far back in time. As at so many Danish manors, ghost legends cling to the house — here especially the Grey Lady, a revenant said to move through the old rooms. Over the centuries the estate passed between families before its land was parcelled out in the 1900s."}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name=EXCLUDED.name, teaser=EXCLUDED.teaser, description=EXCLUDED.description,
  country=EXCLUDED.country, region=EXCLUDED.region, type=EXCLUDED.type,
  lat=EXCLUDED.lat, lng=EXCLUDED.lng, scary=EXCLUDED.scary,
  translations=EXCLUDED.translations, status=EXCLUDED.status, source=EXCLUDED.source;
COMMIT;

-- hauntedplaces-slott-fi-2026-07-14.sql  (finska spökslott & herrgårdar, batch 1)
-- 4 nya platser till Hauntedplaces + Spökkartan (delat Supabase-projekt zffhdjogphqhcttkezsb).
-- Källa: 252 finska slott/kartanot via Wikidata + fi/sv-Wikipedia; spöksägner verifierade mot minst
-- en trovärdig källa (Wikipedia, Kansallismuseo, Kotiliesi/Yle/Apu, VisitSavonlinna). Deduplicerat
-- mot live (1 finsk: Suomenlinna) + data/hauntedplaces-foreign-fi.sql (Helsingfors). Finland var
-- nästan otäckt → 4 flaggskepp. Egen sv+en-text; källornas text återges ALDRIG ordagrant.
-- Idempotent: ON CONFLICT (id) DO UPDATE. Kör i Supabase SQL-editor (projekt zffhdjogphqhcttkezsb).

BEGIN;
INSERT INTO places (id, name, slug, lat, lng, country, region, type, scary, free, bookable, teaser, description, status, source, translations) VALUES
('olavinlinna-savonlinna', 'Olavinlinna (Olofsborg)', 'olavinlinna-savonlinna', 61.8637134, 28.9012379, 'Finland', 'Södra Savolax, Savonlinna', 'Slott', 4, false, true, 'På medeltidsborgen sägs en jungfru, inmurad levande, visa sig på balkongen vid fullmåne – och en vetehinen spelade harpa före varje olycka.', 'Olavinlinna (Olofsborg) reser sig på en holme i Saimen vid Nyslott och är en av Nordens bäst bevarade medeltidsborgar. Slottets mest kända sägen berättar om en ung slottsjungfru som straffades för förräderi genom att muras in levande – vid midnatt under fullmåne sägs hon och hennes officer synas på borgens balkong. Hit hör också berättelsen om den svarta baggen som skrämde bort en fiende och om vetehinen, vattenanden som spelade harpa varje gång en olycka eller plötslig död var i annalkande. Borgen är museum och spelplats för operafestivalen.', 'published', 'wikipedia', '{"en":{"name":"Olavinlinna Castle","teaser":"At this medieval fortress a maiden walled up alive is said to appear on the balcony at full moon — and a water spirit played the harp before every disaster.","description":"Olavinlinna (Olofsborg) rises on an islet in Lake Saimaa at Savonlinna and is one of the Nordic region''s best-preserved medieval castles. Its most famous legend tells of a young castle maiden walled up alive for treachery — at midnight under a full moon she and her officer are said to appear on the castle balcony. There is also the tale of the black ram that scared off an enemy, and of the vetehinen, the water spirit who played the harp whenever disaster or sudden death drew near. The castle is a museum and the stage for the opera festival."}}'::jsonb),
('svarta-slott-mustio-raseborg', 'Svartå slott (Mustion linna)', 'svarta-slott-mustio-raseborg', 60.1579988, 23.8389826, 'Finland', 'Nyland, Raseborg', 'Slott', 4, false, true, 'Den vita frun vandrar med en kandelaber genom rummen, kung Gustav III släpar sina steg i kungsgemaket, och en grå fru skymtar på tredje våningen.', 'Svartå slott (Mustion linna) i Raseborg är ett av Finlands vackraste herrgårdsslott, byggt i nyklassicistisk stil på 1780-talet. Enligt traditionen har slottet fyra spöken. Mest känd är den vita frun som vandrar från rum till rum med en kandelaber – hon kopplas till Jeanette Hisinger, som sägs ha lidit av psykisk ohälsa och hållits inlåst på övervåningen. Kung Gustav III sägs hemsöka kungsgemaket med trötta, släpande steg, och på tredje våningen skymtar en grå fru vars profil setts mot de vita väggarna. Slottet med sin engelska park är öppet för besök.', 'published', 'wikipedia', '{"en":{"name":"Svartå Manor (Mustio)","teaser":"The White Lady wanders the rooms with a candelabra, King Gustav III drags his steps in the royal chamber, and a Grey Woman haunts the third floor.","description":"Svartå Manor (Mustion linna) in Raseborg is one of Finland''s finest manor-castles, built in neoclassical style in the 1780s. By tradition the house has four ghosts. Best known is the White Lady who wanders room to room with a candelabra — linked to Jeanette Hisinger, said to have suffered mental illness and been kept locked upstairs. King Gustav III is said to haunt the royal chamber with weary, dragging steps, and on the third floor a Grey Woman appears, her profile seen against the white walls. The manor and its English park are open to visitors."}}'::jsonb),
('louhisaari-kartano-masku', 'Louhisaari (Louhisaaren kartano)', 'louhisaari-kartano-masku', 60.570916666667, 21.831055555556, 'Finland', 'Egentliga Finland, Masku', 'Herrgård', 4, false, true, 'En svartsjuk make glömde att säga att han låst in sin hustru – hon svalt ihjäl, och den vita frun vandrar än på tredje våningen, ibland med ett barn.', 'Louhisaari (Louhisaaren kartano) i Masku är marskalk Mannerheims barndomshem och en av Finlands få herrgårdar i palatsstil, uppförd på 1650-talet. Sägnen berättar om Anna Sophia Rehbinder, hustru till den svartsjuke Herman Fleming som brukade låsa in henne när han reste bort. En gång glömde han säga till tjänarna – och hon svalt ihjäl. Sedan dess sägs den vita frun vandra på tredje våningen, ofta i sällskap av ett barn som ingen vet vem det är. Besökare har berättat om föremål som flyttar sig, dörrar som öppnas och doften av cigarrök. Herrgården är museum.', 'published', 'wikipedia', '{"en":{"name":"Louhisaari Manor","teaser":"A jealous husband forgot he''d locked his wife away — she starved to death, and the White Lady still walks the third floor, sometimes with a child.","description":"Louhisaari Manor (Louhisaaren kartano) in Masku is Marshal Mannerheim''s childhood home and one of Finland''s few palace-style manors, built in the 1650s. Legend tells of Anna Sophia Rehbinder, wife of the jealous Herman Fleming, who used to lock her away when he travelled. Once he forgot to tell the servants — and she starved to death. Since then the White Lady is said to walk the third floor, often with a child no one can identify. Visitors have described objects that move, doors that open and the scent of cigar smoke. The manor is a museum."}}'::jsonb),
('abo-slott-turku', 'Åbo slott (Turun linna)', 'abo-slott-turku', 60.4352823, 22.2276388, 'Finland', 'Egentliga Finland, Åbo', 'Slott', 3, false, true, 'Nästan alla som arbetat länge på borgen sägs ha sett ett spöke – en man i tidsdräkt i trapporna, och en grönskimrande kvinna med slöja.', 'Åbo slott (Turun linna) vid Aura ås mynning är Finlands största medeltidsborg, grundad på 1280-talet. Många som arbetat länge på borgen säger sig ha sett spöken: på 1980-talet såg både en städare och slottets vaktmästare en man i historisk dräkt i trappan vid fångvaktarens rum. Andra berättar om en grönskimrande kvinnogestalt med slöja, tolkad som en brud eller nunna. En gammal sägen säger att en man murades in levande i en mur som restes under Gustav Vasas tid. Borgen är i dag ett av Finlands mest besökta museer.', 'published', 'wikipedia', '{"en":{"name":"Turku Castle","teaser":"Nearly everyone who has worked here for long is said to have seen a ghost — a man in period dress on the stairs, and a green-shimmering veiled woman.","description":"Turku Castle (Turun linna) at the mouth of the Aura River is Finland''s largest medieval castle, founded in the 1280s. Many long-serving staff say they have seen ghosts: in the 1980s both a cleaner and the castle caretaker saw a man in historical dress on the stairs by the prison guard''s room. Others tell of a green-shimmering veiled female figure, taken for a bride or a nun. An old legend holds that a man was walled up alive in a wall raised in the time of Gustav Vasa. Today the castle is one of Finland''s most visited museums."}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name=EXCLUDED.name, teaser=EXCLUDED.teaser, description=EXCLUDED.description,
  country=EXCLUDED.country, region=EXCLUDED.region, type=EXCLUDED.type,
  lat=EXCLUDED.lat, lng=EXCLUDED.lng, scary=EXCLUDED.scary,
  translations=EXCLUDED.translations, status=EXCLUDED.status, source=EXCLUDED.source;
COMMIT;

-- hauntedplaces-herrgardar-se-2026-07-14.sql  (svenska hemsökta herrgårdar, ANDRA varvet)
-- 4 nya platser till Hauntedplaces + Spökkartan (delat Supabase-projekt zffhdjogphqhcttkezsb).
-- Dedikerat herrgårds-andravarv: webbsök/listkällor per herrgård (Wikipedia missar sägnerna).
-- Deduplicerat mot 1305 live-platser (namn OCH koordinat) + SQL-filerna. De flesta kända svenska
-- herrgårdar var REDAN live (wordpress-importen): Österbybruk, Ericsberg/Pintorpafrun, Toftaholm,
-- Hörle, Blombacka, Blomsholm, Hammars säteri, Görväln (namn-match 1085 m) → uteslutna.
-- Egen sv+en-text; källornas text återges ALDRIG ordagrant. Idempotent: ON CONFLICT (id) DO UPDATE.

BEGIN;
INSERT INTO places (id, name, slug, lat, lng, country, region, type, scary, free, bookable, teaser, description, status, source, translations) VALUES
('von-echstedtska-garden-varmland', 'Von Echstedtska gården', 'von-echstedtska-garden-varmland', 59.2278, 12.7313, 'Sverige', 'Värmland, Säffle', 'Herrgård', 3, false, true, 'Pigan kastade nyckeln mot det vitklädda spöket i farstun – och dödade drängen som ville skrämmas. Hon blev vansinnig och sägs gå igen.', 'Von Echstedtska gården i Västra Smedbyn norr om Säffle är en välbevarad herrgård från 1760-talet, känd för sina takmålningar – och för sin spöksägen. En kväll när pigan låste visthusboden möttes hon i farstun av en vitklädd gestalt med lysande huvud. I skräck kastade hon den tunga nyckeln med all kraft, och gestalten föll ihop. Det visade sig vara drängen, som klätt ut sig i ett vitt lakan med en tändsticka i munnen för att skrämmas. Pigan förlorade förståndet, spärrades in i en flygel och dog där, och sägs sedan dess inte finna ro. Gården är i dag museum.', 'published', 'varmlands-museum', '{"en":{"name":"Von Echstedt Manor","teaser":"The maid hurled the key at the white-clad ghost in the hall — and killed the farmhand who meant to scare her. She lost her mind, and is said to walk still.","description":"Von Echstedt Manor at Västra Smedbyn north of Säffle is a well-preserved 1760s manor famous for its ceiling paintings — and for its ghost legend. One evening as the maid locked the storehouse, she met a white-clad figure with a glowing head in the hall. In terror she hurled the heavy key with all her strength, and the figure collapsed. It was the farmhand, dressed in a white sheet with a match in his mouth to frighten her. The maid lost her mind, was locked in a wing and died there, and since then is said to find no peace. The manor is a museum today."}}'::jsonb),
('noors-slott-knivsta', 'Noors slott', 'noors-slott-knivsta', 59.71611, 17.81972, 'Sverige', 'Uppland, Knivsta', 'Slott', 3, false, true, 'När Heidenstam skrev om Karl XII:s död sägs kungen själv ha stigit fram i dörröppningen – i fältuniform, klockan två på natten.', 'Noors slott är en herrgård från karolinertiden i Knivsta, Uppland. Dess mest kända spökhistoria är kopplad till författaren Verner von Heidenstam, som bodde här ett helt år medan han skrev Karolinerna. En natt vid tvåtiden, just som han avslutade kapitlet om Karl XII:s död vid Fredrikshald, hörde han steg och ett pinglande, skramlande ljud – och i den mörka dörröppningen stod, enligt hans egen skildring, kung Karl XII själv i fältuniform. Slottet är i dag hotell och konferens.', 'published', 'wikipedia', '{"en":{"name":"Noor Castle","teaser":"As Heidenstam wrote of Karl XII’s death, the king himself is said to have stepped into the doorway — in field uniform, at two in the morning.","description":"Noor Castle is a Carolean-era manor in Knivsta, Uppland. Its most famous ghost story involves the writer Verner von Heidenstam, who lived here for a year while writing The Charles Men (Karolinerna). One night around two, just as he finished the chapter on Karl XII’s death at Fredrikshald, he heard footsteps and a jingling, rattling sound — and in the dark doorway stood, by his own account, King Karl XII himself in field uniform. The castle is a hotel and conference venue today."}}'::jsonb),
('gimo-herrgard-uppland', 'Gimo herrgård', 'gimo-herrgard-uppland', 60.17889, 18.17364, 'Sverige', 'Uppland, Östhammar', 'Herrgård', 3, false, true, 'En iskall vind, en dörr som öppnas av sig själv och biljardköer utspridda över golvet – på Gimo sägs drängen Johansson gå igen.', 'Gimo herrgård i Uppland, med huvudbyggnad från 1760-talet, har som sig bör sitt eget spöke. Sägnen utpekar en dräng vid namn Johansson, anställd hos brukspatronen Carl Reuterskiöld på 1800-talet. Personal har berättat om en iskall vind som plötsligt drog genom ett rum strax efter klockan åtta medan dörren till spiraltrappan öppnade sig av sig själv, om släpande steg som följer från rum till rum och om en svart gestalt som glidit förbi och antagit mänsklig form. En gång låg biljardköerna utslängda över golvet. Herrgården är i dag hotell och konferens.', 'published', 'wikipedia', '{"en":{"name":"Gimo Manor","teaser":"An icy wind, a door that opens by itself and billiard cues strewn across the floor — at Gimo the farmhand Johansson is said to walk.","description":"Gimo Manor in Uppland, with a main building from the 1760s, has — as a proper manor should — its own ghost. Legend names a farmhand called Johansson, employed by the ironmaster Carl Reuterskiöld in the 1800s. Staff have told of an icy wind that suddenly swept through a room just after eight while the door to the spiral staircase opened on its own, of dragging footsteps that follow from room to room, and of a black figure that glided past and took human form. Once the billiard cues lay scattered across the floor. The manor is a hotel and conference venue today."}}'::jsonb),
('rankhyttans-herrgard-dalarna', 'Rankhyttans herrgård', 'rankhyttans-herrgard-dalarna', 60.47611, 15.71972, 'Sverige', 'Dalarna, Falun', 'Herrgård', 3, false, true, 'Bergsmannen halshöggs 1534 – och hans hustru sägs ännu vandra som den svarta damen i herrgården.', 'Rankhyttans herrgård utanför Falun i Dalarna vilar på ett gråstensvalv från medeltiden och ägdes under 1500-talets första hälft av bergsmannen Anders Persson. Anders halshöggs i Stockholm 1534, och sägnen berättar att det är hans hustru som går igen i herrgården under namnet den svarta damen. Flera spöken sägs hålla till i de gamla rummen. Herrgården används i dag för konferens och fest.', 'published', 'spokhus', '{"en":{"name":"Rankhyttan Manor","teaser":"The mining master was beheaded in 1534 — and his wife is said to still walk the manor as the Black Lady.","description":"Rankhyttan Manor outside Falun in Dalarna rests on a medieval greystone vault and was owned in the early 1500s by the mining master Anders Persson. Anders was beheaded in Stockholm in 1534, and legend holds that it is his wife who walks the manor as the Black Lady. Several ghosts are said to dwell in the old rooms. The manor is used today for conferences and celebrations."}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name=EXCLUDED.name, teaser=EXCLUDED.teaser, description=EXCLUDED.description,
  country=EXCLUDED.country, region=EXCLUDED.region, type=EXCLUDED.type,
  lat=EXCLUDED.lat, lng=EXCLUDED.lng, scary=EXCLUDED.scary,
  translations=EXCLUDED.translations, status=EXCLUDED.status, source=EXCLUDED.source;
COMMIT;

-- hauntedplaces-slott-uk-2026-07-14.sql  (kända brittiska spökslott, batch 1)
-- 12 nya platser till Hauntedplaces + Spökkartan (delat Supabase-projekt zffhdjogphqhcttkezsb).
-- Kurerade ur den notabla utländska delmängden (data/enrichment-source-notable-foreign.json).
-- Varje sägen webbverifierad mot flera källor (Wikipedia, hauntedrooms.co.uk, spookyisles m.fl.).
-- Dedup mot 1305 live (namn OCH koordinat <500 m): Berry Pomeroy (96 m) och Edinburgh Castle
-- (25 m från befintlig Witches' Well-pin) uteslutna. Egen sv+en-text; källtext återges ALDRIG.
-- Landsetikett 'UK' (matchar appens live-data). Idempotent: ON CONFLICT (id) DO UPDATE.

BEGIN;
INSERT INTO places (id, name, slug, lat, lng, country, region, type, scary, free, bookable, teaser, description, status, source, translations) VALUES
('chillingham-castle-northumberland', 'Chillingham Castle', 'chillingham-castle-northumberland', 55.5258989, -1.9039315, 'UK', 'Northumberland', 'Slott', 5, false, true, 'Den lysande blå pojken grät vid midnatt i Rosa rummet – och vid en renovering hittades barnben inmurade i väggen, svepta i blått tyg.', 'Chillingham Castle i Northumberland kallas ofta Storbritanniens mest hemsökta slott. Dess mest kända spöke är den lysande blå pojken, vars klagande rop hördes vid midnatt i Rosa rummet, följt av ett blått sken. Vid en renovering på 1900-talet fann arbetare barnben inmurade i väggen, svepta i blått tyg. Här sägs också Lady Mary Berkeley vandra, och slottets fängelsehålor bär på en mörk historia.', 'published', 'wikipedia', '{"en":{"name":"Chillingham Castle","teaser":"The radiant Blue Boy cried at midnight in the Pink Room — and a renovation uncovered a child’s bones walled up in blue cloth.","description":"Chillingham Castle in Northumberland is often called Britain’s most haunted castle. Its best-known ghost is the radiant Blue Boy, whose mournful cries were heard at midnight in the Pink Room, followed by a blue glow. During a 20th-century renovation, workers found a child’s bones walled up and wrapped in blue cloth. Lady Mary Berkeley is also said to walk here, and the castle’s dungeons carry a dark history."}}'::jsonb),
('glamis-castle-angus', 'Glamis Castle', 'glamis-castle-angus', 56.620331, -3.001816, 'UK', 'Angus, Skottland', 'Slott', 5, false, true, 'Earl Beardie sägs spela kort med djävulen i ett hemligt rum – och slottet gömmer sägnen om Monstret på Glamis.', 'Glamis Castle i Angus är ett av Skottlands mest sägenomspunna slott. Här sägs Earl Beardie sitta i ett hemligt, igenmurat rum och spela kort med djävulen i evighet, sedan han svurit att spela på sabbaten. Slottet bär också på legenden om Monstret på Glamis, ett vanskapt familjebarn som enligt sägnen hölls dolt, samt om en grå dam som setts i kapellet. Slottet är drottningmoderns barndomshem.', 'published', 'wikipedia', '{"en":{"name":"Glamis Castle","teaser":"Earl Beardie is said to play cards with the Devil in a secret room — and the castle hides the legend of the Monster of Glamis.","description":"Glamis Castle in Angus is one of Scotland’s most legend-haunted castles. Earl Beardie is said to sit in a secret, walled-up room playing cards with the Devil for eternity, after swearing to play on the Sabbath. The castle also carries the legend of the Monster of Glamis, a deformed family child said to have been hidden away, and of a Grey Lady seen in the chapel. It was the childhood home of the Queen Mother."}}'::jsonb),
('muncaster-castle-cumbria', 'Muncaster Castle', 'muncaster-castle-cumbria', 54.3546391, -3.3807014, 'UK', 'Cumbria', 'Slott', 4, false, true, 'I gobelängrummet hörs ett gråtande barn och en sjungande kvinna – och Vita damen sägs vara Mary Bragg, mördad vid slottsporten på 1800-talet.', 'Muncaster Castle i Cumbria är ett vallfärdsmål för spökforskare. I det så kallade gobelängrummet berättar besökare om ett gråtande barn och en sjungande kvinna. Slottets vita dam sägs vara Mary Bragg, en ung kvinna som mördades nära huvudporten i början av 1800-talet. Slottet, som ännu bebos av familjen Pennington, är öppet för besök.', 'published', 'wikipedia', '{"en":{"name":"Muncaster Castle","teaser":"A crying child and a singing woman are heard in the Tapestry Room — and the White Lady is said to be Mary Bragg, murdered by the gate in the 1800s.","description":"Muncaster Castle in Cumbria is a magnet for paranormal researchers. In the Tapestry Room, visitors report a crying child and a singing woman. The castle’s White Lady is said to be Mary Bragg, a young woman murdered near the main gate in the early 1800s. Still home to the Pennington family, the castle is open to visitors."}}'::jsonb),
('warwick-castle-warwickshire', 'Warwick Castle', 'warwick-castle-warwickshire', 52.2795271, -1.5844827, 'UK', 'Warwickshire', 'Slott', 4, false, true, 'Sir Fulke Greville knivhöggs av sin tjänare 1628 – och sägs ännu vandra i Watergate-tornet där han dog.', 'Warwick Castle är ett av Englands mäktigaste medeltidsslott. Dess mest kända spöke är Sir Fulke Greville, en tidigare slottsherre som 1628 knivhöggs till döds av sin tjänare Ralph Haywood i en tvist om testamentet. Sedan dess sägs hans vålnad vandra genom slottet, särskilt i Watergate-tornet – i dag kallat Ghost Tower – där han tillbringade sina sista plågsamma dygn.', 'published', 'wikipedia', '{"en":{"name":"Warwick Castle","teaser":"Sir Fulke Greville was stabbed by his servant in 1628 — and is said to still walk the Watergate Tower where he died.","description":"Warwick Castle is one of England’s mightiest medieval castles. Its best-known ghost is Sir Fulke Greville, a former lord of the castle stabbed to death in 1628 by his servant Ralph Haywood in a dispute over his will. Since then his apparition is said to wander the castle, especially the Watergate Tower — today called the Ghost Tower — where he spent his last agonising days."}}'::jsonb),
('tutbury-castle-staffordshire', 'Tutbury Castle', 'tutbury-castle-staffordshire', 52.8597616, -1.6903381, 'UK', 'Staffordshire', 'Slott', 4, false, true, 'Maria Stuart hölls fången här och sägs gå igen – 2004 ska hon ha visat sig för ett fyrtiotal personer på södra tornet.', 'Tutbury Castle i Staffordshire var ett av de fängelser där Maria Stuart hölls inspärrad. Hon sägs avsky platsen och gå igen som ett av slottets spöken. Här berättas också om en gestalt i full rustning, en vit dam och ett barn. År 2004 ska Marias vålnad ha visat sig för ett fyrtiotal personer på södra tornet. Ruinen är öppen för besök.', 'published', 'wikipedia', '{"en":{"name":"Tutbury Castle","teaser":"Mary Queen of Scots was imprisoned here and is said to walk — in 2004 her apparition reportedly appeared to some forty people on the South Tower.","description":"Tutbury Castle in Staffordshire was one of the prisons where Mary Queen of Scots was held. She is said to despise the place and to return as one of its ghosts. There are also accounts of a figure in full armour, a White Lady and a child. In 2004 Mary’s apparition reportedly appeared to some forty people atop the South Tower. The ruin is open to visitors."}}'::jsonb),
('dover-castle-kent', 'Dover Castle', 'dover-castle-kent', 51.1289759, 1.3228764, 'UK', 'Kent', 'Slott', 4, false, true, 'En huvudlös trumslagarpojke sägs vandra i tunnlarna – mördad och halshuggen medan han bar en summa pengar.', 'Dover Castle i Kent, "nyckeln till England", vilar på ett nät av tunnlar. Dess mest kända spöke är en huvudlös trumslagarpojke som enligt sägnen mördades och halshöggs medan han bar en summa pengar genom gångarna. Hans trumslag hörs ännu från vallarna. Slottet är ett av Englands mest omtalade hemsökta.', 'published', 'wikipedia', '{"en":{"name":"Dover Castle","teaser":"A headless drummer boy is said to walk the tunnels — murdered and beheaded while carrying a sum of money.","description":"Dover Castle in Kent, \"the key to England\", rests on a web of tunnels. Its most famous ghost is a headless drummer boy who, by legend, was murdered and beheaded while carrying a sum of money through the passages. His drumming is still heard on the battlements. The castle is one of England’s most talked-about haunted sites."}}'::jsonb),
('bamburgh-castle-northumberland', 'Bamburgh Castle', 'bamburgh-castle-northumberland', 55.609444, -1.7112671, 'UK', 'Northumberland', 'Slott', 3, false, true, 'Gröna Jane skickades att tigga mat, visades bort och föll död med sitt barn i famnen – ännu sägs hon vandra vid slottet.', 'Bamburgh Castle reser sig dramatiskt över Northumberlands kust. Slottets gröna dam, kallad Gröna Jane, sägs vara en fattig flicka som skickades att tigga mat vid slottet men visades bort av vakterna. Utmattad föll hon till sin död med sitt spädbarn i famnen. Här berättas också om en rosa dam, slottets äldsta spöke. Borgen är öppen för besök.', 'published', 'wikipedia', '{"en":{"name":"Bamburgh Castle","teaser":"Green Jane was sent to beg for food, turned away, and fell to her death with her baby — she is still said to walk the castle.","description":"Bamburgh Castle rises dramatically above the Northumberland coast. Its Green Lady, called Green Jane, is said to be a poor girl sent to beg for food at the castle but turned away by the guards. Exhausted, she fell to her death with her infant in her arms. There is also a Pink Lady, the castle’s oldest ghost. The fortress is open to visitors."}}'::jsonb),
('stirling-castle-stirling', 'Stirling Castle', 'stirling-castle-stirling', 56.123717, -3.947873, 'UK', 'Stirling, Skottland', 'Slott', 3, false, true, 'Att se Gröna damen sägs varsla om eld – hon var tjänarinna åt Maria Stuart och dog själv i en brand.', 'Stirling Castle, ett av Skottlands största slott, hemsöks enligt traditionen av Gröna damen. Hon sägs ha varit tjänarinna åt Maria Stuart, och att se henne varslar om eld eller olycka – enligt sägnen dog hon själv i en brand. Här går också en rosa dam. Slottet, där flera skotska kungar krönts, är öppet för besök.', 'published', 'wikipedia', '{"en":{"name":"Stirling Castle","teaser":"Seeing the Green Lady is said to warn of fire — she was a maid to Mary Queen of Scots and died in a blaze.","description":"Stirling Castle, one of Scotland’s largest, is by tradition haunted by the Green Lady. She is said to have been a maid to Mary Queen of Scots, and seeing her warns of fire or disaster — by legend she herself died in a blaze. A Pink Lady walks here too. The castle, where several Scottish kings were crowned, is open to visitors."}}'::jsonb),
('tamworth-castle-staffordshire', 'Tamworth Castle', 'tamworth-castle-staffordshire', 52.6325994, -1.6967458, 'UK', 'Staffordshire', 'Slott', 3, false, true, 'Svarta damen sägs vara nunnan Editha, vars kloster fördrevs – och en vit dam vandrar och söker sin mördade älskade.', 'Tamworth Castle har två kända spöken. Svarta damen sägs vara nunnan Editha, som grundade sin orden på 800-talet och vars systrar enligt sägnen fördrevs från klostret av Robert de Marmion. Vita damen ska ha kastats i tornet av Sir Tarquin, förälskat sig i honom, och vandrar nu och söker sin älskade. Den välbevarade normandiska borgen är i dag museum.', 'published', 'wikipedia', '{"en":{"name":"Tamworth Castle","teaser":"The Black Lady is said to be the nun Editha, whose convent was expelled — and a White Lady walks seeking her murdered love.","description":"Tamworth Castle has two well-known ghosts. The Black Lady is said to be the nun Editha, who founded her order in the 9th century and whose sisters were, by legend, expelled from their convent by Robert de Marmion. The White Lady was reputedly thrown into the tower by Sir Tarquin, fell in love with him, and now walks seeking her lost love. The well-preserved Norman castle is a museum today."}}'::jsonb),
('dudley-castle-west-midlands', 'Dudley Castle', 'dudley-castle-west-midlands', 52.5145004, -2.0790075, 'UK', 'West Midlands', 'Slott', 3, false, true, 'Gråa damen sägs vara Dorothy Beaumont, död strax efter en förlossning – hennes sista önskningar uppfylldes aldrig.', 'Dudley Castle i West Midlands hemsöks enligt traditionen av Gråa damen, som sägs vara Dorothy Beaumont. Hon dog strax efter att ha fött barn på slottet och sägs inte finna ro, eftersom de önskningar hon uttalade på sin dödsbädd aldrig uppfylldes. En besökare påstod sig ha fångat henne på bild. Slottet ligger i dag inom Dudley djurpark.', 'published', 'wikipedia', '{"en":{"name":"Dudley Castle","teaser":"The Grey Lady is said to be Dorothy Beaumont, dead soon after childbirth — her dying wishes never granted.","description":"Dudley Castle in the West Midlands is by tradition haunted by the Grey Lady, said to be Dorothy Beaumont. She died soon after giving birth at the castle and is said to find no rest, because the wishes she voiced on her deathbed were never granted. One visitor claimed to have caught her on camera. The castle today lies within Dudley Zoo."}}'::jsonb),
('windsor-castle-berkshire', 'Windsor Castle', 'windsor-castle-berkshire', 51.4837886, -0.6040419, 'UK', 'Berkshire', 'Slott', 3, false, true, 'Anne Boleyns vålnad sägs synas i fönstren – och i den kringliggande parken rider den spöklike Herne the Hunter.', 'Windsor Castle, den brittiska monarkins äldsta bebodda slott, bär på flera spöksägner. Anne Boleyn, halshuggen av Henrik VIII, sägs synas i fönstren, och kungen själv ska höras släpa sina steg genom korridorerna. I Windsor Great Park rider enligt sägnen Herne the Hunter, en spöklik jägare med hjorthorn vars uppenbarelse varslar om olycka.', 'published', 'wikipedia', '{"en":{"name":"Windsor Castle","teaser":"Anne Boleyn’s apparition is said to appear at the windows — and in the surrounding park rides the ghostly Herne the Hunter.","description":"Windsor Castle, the oldest inhabited castle of the British monarchy, carries several ghost legends. Anne Boleyn, beheaded by Henry VIII, is said to appear at the windows, and the king himself is said to be heard dragging his steps through the corridors. In Windsor Great Park, legend has it, rides Herne the Hunter, a spectral huntsman with antlers whose appearance warns of misfortune."}}'::jsonb),
('highclere-castle-berkshire', 'Highclere Castle', 'highclere-castle-berkshire', 51.4100297, -1.3044986, 'UK', 'Berkshire', 'Slott', 3, false, true, 'På slottet som spelar Downton Abbey sägs en olycklig betjänt gå igen – ägaren själv har berättat om spöken.', 'Highclere Castle i Berkshire är känt som inspelningsplats för Downton Abbey. Slottet, hem för familjen Carnarvon – vars femte earl var med och öppnade Tutankhamuns grav 1922 – sägs hysa flera spöken. Lady Carnarvon har själv berättat om en olycklig betjänt vars vålnad följt efter henne genom rummen. Slottet är öppet för besök delar av året.', 'published', 'wikipedia', '{"en":{"name":"Highclere Castle","teaser":"At the castle that plays Downton Abbey an unhappy footman is said to walk — the owner herself has described ghosts.","description":"Highclere Castle in Berkshire is famous as the filming location for Downton Abbey. The castle, home to the Carnarvon family — whose fifth Earl helped open Tutankhamun’s tomb in 1922 — is said to hold several ghosts. Lady Carnarvon has herself described an unhappy footman whose apparition followed her through the rooms. The castle is open to visitors part of the year."}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name=EXCLUDED.name, teaser=EXCLUDED.teaser, description=EXCLUDED.description,
  country=EXCLUDED.country, region=EXCLUDED.region, type=EXCLUDED.type,
  lat=EXCLUDED.lat, lng=EXCLUDED.lng, scary=EXCLUDED.scary,
  translations=EXCLUDED.translations, status=EXCLUDED.status, source=EXCLUDED.source;
COMMIT;

-- hauntedplaces-intl-2026-07-14.sql  (världskända utländska spökplatser, batch 2)
-- 12 nya platser (10 USA + 2 UK) till Hauntedplaces + Spökkartan (projekt zffhdjogphqhcttkezsb).
-- Kurerade ur den notabla utländska delmängden; varje sägen webbverifierad (Wikipedia, hauntedrooms,
-- US Ghost Adventures m.fl.). Omtvistade legender skrivs som legender. Dedup mot 1305 live (namn+koordinat):
-- redan live t.ex. Queen Mary, Whaley House, Bird Cage, Alcatraz, Lemp, Villisca -> ej med.
-- Egen sv+en-text; källtext återges ALDRIG. Idempotent: ON CONFLICT (id) DO UPDATE.

BEGIN;
INSERT INTO places (id, name, slug, lat, lng, country, region, type, scary, free, bookable, teaser, description, status, source, translations) VALUES
('stanley-hotel-colorado', 'The Stanley Hotel', 'stanley-hotel-colorado', 40.383371, -105.5191728, 'USA', 'Colorado', 'Hotell', 4, false, true, 'Hotellet som inspirerade The Shining – i rum 217 sägs städerskan Elizabeth Wilson gå igen efter en explosion 1911.', 'The Stanley Hotel i Estes Park, Colorado, inspirerade Stephen King till The Shining efter en natt i rum 217. Just det rummet knyts till städerskan Elizabeth Wilson, som 1911 slungades genom golvet av en gasexplosion men överlevde – hennes vänliga vålnad sägs ännu ordna gästernas tillhörigheter. Från balsalen hörs pianotoner när ingen spelar, och barnröster i korridorerna på övervåningen.', 'published', 'wikipedia', '{"en":{"name":"The Stanley Hotel","teaser":"The hotel that inspired The Shining — in room 217 the housekeeper Elizabeth Wilson is said to linger after a 1911 explosion.","description":"The Stanley Hotel in Estes Park, Colorado, inspired Stephen King to write The Shining after a night in room 217. That room is tied to housekeeper Elizabeth Wilson, thrown through the floor by a 1911 gas explosion yet surviving — her friendly ghost is said to still tidy guests’ belongings. Piano notes drift from the ballroom when no one plays, and children’s voices are heard in the upstairs halls."}}'::jsonb),
('eastern-state-penitentiary-pennsylvania', 'Eastern State Penitentiary', 'eastern-state-penitentiary-pennsylvania', 39.9683364, -75.1726648, 'USA', 'Pennsylvania', 'Fängelse', 5, false, true, 'I det övergivna fängelset darrar skuggestalter längs cellblocken – en låssmed berättade om en kraft som grep tag i honom.', 'Eastern State Penitentiary i Philadelphia, en gång världens dyraste fängelse med sin isoleringsregim, räknas till USA:s mest hemsökta. Besökare berättar om kacklande skratt i cellblock 12, skuggestalter som glider längs väggarna i block 6 och ansikten i block 4. En underhållsarbetare, Gary Johnson, sade sig ha känt en kraft gripa tag i honom så hårt att han inte kunde röra sig. Ruinen är i dag museum.', 'published', 'wikipedia', '{"en":{"name":"Eastern State Penitentiary","teaser":"In the abandoned prison shadow figures flit along the cellblocks — a locksmith told of a force that seized him.","description":"Eastern State Penitentiary in Philadelphia, once the world’s most expensive prison with its regime of solitude, ranks among America’s most haunted. Visitors report cackling laughter in Cellblock 12, shadow figures sliding along the walls of Block 6, and faces in Block 4. A maintenance worker, Gary Johnson, said a force gripped him so hard he could not move. The ruin is a museum today."}}'::jsonb),
('waverly-hills-sanatorium-kentucky', 'Waverly Hills Sanatorium', 'waverly-hills-sanatorium-kentucky', 38.1302387, -85.8411866, 'USA', 'Kentucky', 'Sanatorium', 5, false, true, 'Genom "dödstunneln" firades tusentals lik ner i hemlighet – och i rum 502 sägs en röst skrika "Get out!".', 'Waverly Hills Sanatorium i Louisville, Kentucky, var ett tuberkulossjukhus där tusentals dog under "den vita pestens" år. De döda firades i hemlighet ner för berget genom den så kallade dödstunneln (the body chute). Där berättar besökare om släpande ljud, viskningar och gestalter i mörkret, och i det ökända rum 502 ska en osynlig röst ha skrikit åt folk att ge sig av. Byggnaden är ett av USA:s mest ökända spökhus.', 'published', 'wikipedia', '{"en":{"name":"Waverly Hills Sanatorium","teaser":"Through the \"death tunnel\" thousands of bodies were lowered in secret — and in Room 502 a voice is said to scream \"Get out!\".","description":"Waverly Hills Sanatorium in Louisville, Kentucky, was a tuberculosis hospital where thousands died during the years of the \"white plague\". The dead were lowered down the hillside in secret through the so-called death tunnel, or body chute. There visitors describe dragging sounds, whispers and figures in the dark, and in the infamous Room 502 an unseen voice is said to have screamed at people to leave. The building is one of America’s most notorious haunted sites."}}'::jsonb),
('myrtles-plantation-louisiana', 'Myrtles Plantation', 'myrtles-plantation-louisiana', 30.8034022, -91.3880495, 'USA', 'Louisiana', 'Herrgård', 4, false, true, 'Sägnen berättar om slavinnan Chloe, som förlorade ett öra och sägs vandra i sin gröna turban – men historiker betvivlar historien.', 'Myrtles Plantation i St. Francisville, Louisiana, från 1796, kallas ofta ett av USA:s mest hemsökta hem. Den mest kända sägnen handlar om slavinnan Chloe, som enligt berättelsen fick ett öra avskuret och bar en grön turban för att dölja det, och som ska ha förgiftat familjens barn med oleander. Historiker påpekar att det saknas belägg för Chloe och att dödsfallen berodde på gula febern – men på plantagen berättas ännu om speglar, spöklika barn och gestalter på verandan.', 'published', 'wikipedia', '{"en":{"name":"Myrtles Plantation","teaser":"Legend tells of the enslaved woman Chloe, who lost an ear and is said to walk in her green turban — though historians doubt the tale.","description":"Myrtles Plantation in St. Francisville, Louisiana, built in 1796, is often called one of America’s most haunted homes. Its best-known legend concerns Chloe, an enslaved woman said to have had an ear cut off and to have worn a green turban to hide it, and to have poisoned the family’s children with oleander. Historians note there is no record of Chloe and that the deaths were from yellow fever — yet the plantation still tells of mirrors, ghostly children and figures on the veranda."}}'::jsonb),
('winchester-mystery-house-california', 'Winchester Mystery House', 'winchester-mystery-house-california', 37.3183318, -121.9510491, 'USA', 'California', 'Herrgård', 4, false, true, 'Änkan Sarah Winchester lät bygga i 36 år på ett hus med trappor som slutar i tak – enligt sägnen för att förvirra andarna efter gevärens offer.', 'Winchester Mystery House i San Jose, Kalifornien, byggdes om oavbrutet i 36 år av änkan Sarah Winchester. Enligt den populära sägnen höll hon séanser och lät bygga labyrintiska korridorer, trappor som slutar i tak och dörrar som öppnas mot tomma intet för att förvirra andarna efter alla som dödats av familjens Winchestergevär. Historiker menar att de udda dragen mest beror på jordbävningsskador och ständiga ombyggnader – men huset förblir en av USA:s mest berömda spökbyggnader.', 'published', 'wikipedia', '{"en":{"name":"Winchester Mystery House","teaser":"The widow Sarah Winchester built for 36 years a house with stairs that end at the ceiling — by legend, to confuse the ghosts of the rifle’s victims.","description":"Winchester Mystery House in San Jose, California, was rebuilt without pause for 36 years by the widow Sarah Winchester. By popular legend she held séances and built labyrinthine corridors, stairs that end at the ceiling and doors that open onto nothing, to confuse the spirits of all killed by the family’s Winchester rifles. Historians hold the oddities owe more to earthquake damage and constant remodelling — yet the house remains one of America’s most famous haunted buildings."}}'::jsonb),
('franklin-castle-ohio', 'Franklin Castle', 'franklin-castle-ohio', 41.4857366, -81.7165798, 'USA', 'Ohio', 'Hus', 3, false, true, 'Ohios mest hemsökta hus – där bankiren Tiedemann såg flera i sin familj dö, och gråt sägs höras ur väggarna.', 'Franklin Castle (Tiedemann-huset) i Cleveland, Ohio, byggt på 1880-talet av bankiren Hannes Tiedemann, kallas ofta delstatens mest hemsökta hem. Tiedemann drabbades av en rad tragedier då flera i familjen dog, och sedan 1960-talet berättas om barngråt ur väggarna, steg i tomma rum och en kvinna i svart. Den mörka stenbyggnaden i Queen Anne-stil är en klassiker i amerikansk spökfolklore.', 'published', 'wikipedia', '{"en":{"name":"Franklin Castle","teaser":"Ohio’s most haunted house — where the banker Tiedemann saw several of his family die, and crying is said to seep from the walls.","description":"Franklin Castle (the Tiedemann House) in Cleveland, Ohio, built in the 1880s by banker Hannes Tiedemann, is often called the state’s most haunted home. Tiedemann suffered a string of tragedies as several family members died, and since the 1960s there have been accounts of a child’s crying from the walls, footsteps in empty rooms and a woman in black. The dark Queen Anne stone house is a classic of American ghost lore."}}'::jsonb),
('uss-hornet-california', 'USS Hornet', 'uss-hornet-california', 37.7726482, -122.3025322, 'USA', 'California', 'Museum', 3, false, true, 'På det hemsökta hangarfartyget dog över 300 man – och en sjöman i vit paraduniform sägs ännu synas ombord.', 'USS Hornet, ett hangarfartyg från andra världskriget som nu är museum i Alameda, Kalifornien, räknas till USA:s mest hemsökta fartyg. Över 300 man förlorade livet ombord, och besökare berättar om "the Dress Whites Ghost" – en sjöman i vit paraduniform – samt om steg, röster och dörrar som rör sig av sig själva. Fartyget håller regelbundna spökvakor för besökare.', 'published', 'wikipedia', '{"en":{"name":"USS Hornet","teaser":"On the haunted aircraft carrier over 300 men died — and a sailor in white dress uniform is said to still appear aboard.","description":"USS Hornet, a World War II aircraft carrier now a museum in Alameda, California, is counted among America’s most haunted ships. Over 300 men lost their lives aboard, and visitors tell of the \"Dress Whites Ghost\" — a sailor in white dress uniform — as well as footsteps, voices and doors that move by themselves. The ship hosts regular overnight ghost watches."}}'::jsonb),
('molly-brown-house-colorado', 'Molly Brown House', 'molly-brown-house-colorado', 39.737494, -104.980736, 'USA', 'Colorado', 'Museum', 2, false, true, 'Titanic-överlevaren Molly Browns hem – där doften av J.J. Browns pipa dröjer och möbler flyttar sig.', 'Molly Brown House i Denver, Colorado, var hem för Margaret "Molly" Brown, som överlevde Titanics förlisning. I dag är det museum, och besökare och personal berättar om doften av piprök – tillskriven maken J.J. Brown – om möbler som flyttat sig och en kvinna i viktoriansk klädsel som skymtat medan hon ordnat i rummen. Ett stillsamt men välbelagt spökhus.', 'published', 'wikipedia', '{"en":{"name":"Molly Brown House","teaser":"Titanic survivor Molly Brown’s home — where the scent of J.J. Brown’s pipe lingers and furniture rearranges itself.","description":"The Molly Brown House in Denver, Colorado, was home to Margaret \"Molly\" Brown, who survived the sinking of the Titanic. Now a museum, visitors and staff tell of the scent of pipe smoke — attributed to her husband J.J. Brown — of furniture that has moved, and a woman in Victorian dress glimpsed tidying the rooms. A gentle but well-attested haunting."}}'::jsonb),
('point-lookout-lighthouse-maryland', 'Point Lookout Lighthouse', 'point-lookout-lighthouse-maryland', 38.0387818, -76.3220739, 'USA', 'Maryland', 'Fyr', 4, false, true, 'Fyren står på platsen för inbördeskrigets största fångläger – en fyrvaktarhustru och en sydstatssoldat sägs gå igen.', 'Point Lookout Lighthouse i Maryland reser sig på platsen för inbördeskrigets största fångläger, där tusentals dog. Fyren kallas ofta USA:s mest hemsökta. Den första fyrvaktarens hustru, Ann Davis, som dog i lanterninrummet, sägs synas överst i trappan i blå kjol och vit blus, och parkvakter berättar om en sydstatssoldat som skymtar i backspeglar. En paranormal utredare räknade 1980 till 24 andar i huset.', 'published', 'wikipedia', '{"en":{"name":"Point Lookout Lighthouse","teaser":"The lighthouse stands on the Civil War’s largest prison camp — a keeper’s wife and a Confederate soldier are said to walk.","description":"Point Lookout Lighthouse in Maryland rises on the site of the Civil War’s largest prison camp, where thousands died. It is often called America’s most haunted lighthouse. Ann Davis, the first keeper’s wife, who died in the lantern room, is said to appear at the top of the stairs in a blue skirt and white blouse, and rangers tell of a Confederate soldier glimpsed in rear-view mirrors. A paranormal investigator counted 24 spirits in the house in 1980."}}'::jsonb),
('fort-delaware-delaware', 'Fort Delaware', 'fort-delaware-delaware', 39.578484, -75.587367, 'USA', 'Delaware', 'Fästning', 3, false, true, 'På ökuborgen där inbördeskrigets fångar hölls dog omkring 2 500 man – kalla fläckar och gestalter sägs dröja kvar.', 'Fort Delaware på Pea Patch Island tjänade under inbördeskriget som fångläger för sydstatssoldater. Nära 13 000 hölls samtidigt och omkring 2 500 dog under svåra förhållanden. Besökare berättar om kalla fläckar, gestalter och obegripliga ljud i de gamla valven. Fästningen nås med färja och är i dag ett populärt mål för spökvakor.', 'published', 'wikipedia', '{"en":{"name":"Fort Delaware","teaser":"At the island fort that held Civil War prisoners some 2,500 men died — cold spots and figures are said to linger.","description":"Fort Delaware on Pea Patch Island served during the Civil War as a prison camp for Confederate soldiers. Nearly 13,000 were held at once and around 2,500 died in harsh conditions. Visitors tell of cold spots, figures and unexplained sounds in the old vaults. Reached by ferry, the fort is today a popular destination for ghost watches."}}'::jsonb),
('ancient-ram-inn-gloucestershire', 'Ancient Ram Inn', 'ancient-ram-inn-gloucestershire', 51.6378241, -2.3547251, 'UK', 'Gloucestershire', 'Värdshus', 5, false, true, 'Ett av Storbritanniens mest hemsökta hus – i "Häxans rum" sägs en bränd häxa från 1500-talet dröja kvar.', 'Ancient Ram Inn i Wotton-under-Edge, Gloucestershire, brukar kallas Storbritanniens mest hemsökta byggnad. Enligt sägnen sökte en häxa skydd här på 1500-talet undan häxjägarna men greps och brändes – rummet där hon gömde sig kallas i dag Häxans rum, där hennes vålnad sägs finnas kvar. Besökare berättar om en osynlig kraft, röster och känslan av att bli vidrörd. Huset vilar på en mycket äldre kultplats.', 'published', 'wikipedia', '{"en":{"name":"Ancient Ram Inn","teaser":"One of Britain’s most haunted houses — in the \"Witch’s Room\" a witch burned in the 1500s is said to linger.","description":"The Ancient Ram Inn in Wotton-under-Edge, Gloucestershire, is often called Britain’s most haunted building. By legend a witch sought refuge here in the 1500s from the witch-hunters but was seized and burned — the room where she hid is today called the Witch’s Room, where her ghost is said to remain. Visitors tell of an unseen force, voices and the feeling of being touched. The house sits on a far older ritual site."}}'::jsonb),
('ordsall-hall-salford', 'Ordsall Hall', 'ordsall-hall-salford', 53.469393, -2.277508, 'UK', 'Salford', 'Herrgård', 3, false, true, 'Den vita damen sägs vara Margaret Radclyffe, som dog av krossat hjärta 1599 och vandrar med ett ljus.', 'Ordsall Hall i Salford är en tudorherrgård vars mest kända spöke är den vita damen. Hon sägs vara Margaret Radclyffe, som bodde här i slutet av 1500-talet och dog av sorg 1599 efter att ha förlorat sin bror. Hon har rapporterats vandra genom salarna och Star Chamber med ett ljus i handen. Herrgården är i dag museum med egna spökberättelser.', 'published', 'wikipedia', '{"en":{"name":"Ordsall Hall","teaser":"The White Lady is said to be Margaret Radclyffe, who died of a broken heart in 1599 and walks carrying a candle.","description":"Ordsall Hall in Salford is a Tudor manor whose best-known ghost is the White Lady. She is said to be Margaret Radclyffe, who lived here in the late 1500s and died of grief in 1599 after losing her brother. She has been reported walking the halls and the Star Chamber holding a candle. The hall is a museum today, with ghost stories of its own."}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name=EXCLUDED.name, teaser=EXCLUDED.teaser, description=EXCLUDED.description,
  country=EXCLUDED.country, region=EXCLUDED.region, type=EXCLUDED.type,
  lat=EXCLUDED.lat, lng=EXCLUDED.lng, scary=EXCLUDED.scary,
  translations=EXCLUDED.translations, status=EXCLUDED.status, source=EXCLUDED.source;
COMMIT;

